version: '3'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Api\Dockerfile

  user.api:
    image: user.api
    build:
      context: .
      dockerfile: ..\User.Api\Dockerfile


  balance.api:
    image: balance.api
    build:
      context: .
      dockerfile: Balance.Api\Dockerfile

